version: '3.6'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php-fpm:
    user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./app:/var/www/html
#      - ./app/vendor:/var/www/html/vendor:delegated

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1450